spring:
  application:
    name: auth-git
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/testdb

app:
  security:
    public-urls: "/users/register, /users/login, /h2-console, /error, /, /health-check"
