spring:
  application:
    name: auth-git
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/testdb

  security:
    user:
      name: user
      password: "$2a$10$mWwlwwjO2hWMAp866vmaZOSCSMdj0y7PWeucRVgDDC2fWo/7k6PhG"

app:
  security:
    public-urls: "/users/register, /users/login, /h2-console, /error, /, /health-check"
